import { useState } from "react";
import {
    Code2,
    Play,
    Save,
    Download,
    Copy,
    Sparkles,
    Database,
    Table,
    AlertTriangle,
    CheckCircle,
    ChevronRight,
    ChevronDown,
    Lightbulb,
    RefreshCw,
    FileCode,
    Settings,
    Maximize2,
} from "lucide-react";
import { Button } from "@/components/ui/button";
import { cn } from "@/lib/utils";

const sampleSQL = `-- Churn Prediction Data Pipeline
-- Auto-generated by VDS Co-Pilot

-- Step 1: Data Cleanup
WITH cleaned_customers AS (
  SELECT 
    customer_id,
    email,
    COALESCE(full_name, 'Unknown') AS full_name,
    created_at,
    CASE 
      WHEN segment IS NULL THEN 'Standard'
      ELSE segment 
    END AS segment
  FROM raw.customers
  WHERE created_at >= DATEADD(month, -12, CURRENT_DATE)
    AND email IS NOT NULL
),

-- Step 2: Transaction Features
transaction_features AS (
  SELECT 
    c.customer_id,
    COUNT(t.id) AS total_orders,
    SUM(t.amount) AS total_spend,
    AVG(t.amount) AS avg_order_value,
    MAX(t.created_at) AS last_order_date,
    DATEDIFF(day, MAX(t.created_at), CURRENT_DATE) AS days_since_last_order
  FROM cleaned_customers c
  LEFT JOIN raw.transactions t ON c.customer_id = t.customer_id
  GROUP BY c.customer_id
),

-- Step 3: Session Features  
session_features AS (
  SELECT
    customer_id,
    COUNT(*) AS total_sessions,
    AVG(duration_seconds) / 60.0 AS avg_session_duration_mins,
    SUM(page_views) AS total_page_views
  FROM raw.sessions
  WHERE created_at >= DATEADD(day, -90, CURRENT_DATE)
  GROUP BY customer_id
),

-- Step 4: Label Definition
labeled_customers AS (
  SELECT
    c.*,
    tf.*,
    sf.*,
    CASE 
      WHEN tf.days_since_last_order >= 30 THEN 1 
      ELSE 0 
    END AS is_churned
  FROM cleaned_customers c
  LEFT JOIN transaction_features tf USING (customer_id)
  LEFT JOIN session_features sf USING (customer_id)
)

-- Final Output
SELECT * FROM labeled_customers
ORDER BY customer_id;`;

const copilotHints = [
    { type: "warning", message: "Consider adding a time-based split for training/validation to prevent leakage." },
    { type: "suggestion", message: "The join on sessions may result in NULL values. Use COALESCE for default values." },
    { type: "info", message: "This query will process approximately 124K rows from cleaned_customers." },
];

const dataPreview = [
    { customer_id: "CUS-001", full_name: "Sarah Johnson", segment: "Enterprise", total_orders: 24, total_spend: 12400, is_churned: 0 },
    { customer_id: "CUS-002", full_name: "Michael Chen", segment: "Growth", total_orders: 8, total_spend: 3200, is_churned: 1 },
    { customer_id: "CUS-003", full_name: "Emma Williams", segment: "Enterprise", total_orders: 45, total_spend: 28900, is_churned: 0 },
    { customer_id: "CUS-004", full_name: "James Rodriguez", segment: "Standard", total_orders: 3, total_spend: 890, is_churned: 1 },
    { customer_id: "CUS-005", full_name: "Lisa Park", segment: "Enterprise", total_orders: 67, total_spend: 45200, is_churned: 0 },
];

const profilingStats = [
    { column: "customer_id", nullPct: 0, distinct: 124521, type: "string" },
    { column: "total_orders", nullPct: 2.3, distinct: 89, type: "int" },
    { column: "total_spend", nullPct: 2.3, distinct: 8942, type: "float" },
    { column: "is_churned", nullPct: 0, distinct: 2, type: "int" },
];

export function SQLNotebook() {
    const [sql, setSQL] = useState(sampleSQL);
    const [isRunning, setIsRunning] = useState(false);
    const [showResults, setShowResults] = useState(true);

    const runQuery = () => {
        setIsRunning(true);
        setTimeout(() => {
            setIsRunning(false);
            setShowResults(true);
        }, 1500);
    };

    return (
        <div className="h-full flex bg-background animate-fade-in">
            {/* Main Editor */}
            <div className="flex-1 flex flex-col min-w-0">
                {/* Toolbar */}
                <div className="h-16 border-b border-border px-6 flex items-center justify-between bg-card/30 backdrop-blur-sm">
                    <div className="flex items-center gap-4">
                        <div className="p-2 rounded-xl bg-primary/10 border border-primary/20">
                            <Code2 className="w-5 h-5 text-primary" />
                        </div>
                        <div>
                            <div className="flex items-center gap-2">
                                <span className="font-bold text-foreground">churn_pipeline.sql</span>
                                <span className="px-2 py-0.5 text-[10px] font-bold rounded bg-emerald-400/10 text-emerald-400 uppercase tracking-tighter">
                                    Syncing
                                </span>
                            </div>
                            <p className="text-[10px] text-muted-foreground uppercase tracking-widest mt-0.5">Last edited 2m ago</p>
                        </div>
                    </div>
                    <div className="flex items-center gap-2">
                        <Button variant="outline" size="sm" className="gap-2 rounded-lg h-9 border-border bg-card/50">
                            <Sparkles className="w-4 h-4 text-primary" />
                            Explain
                        </Button>
                        <Button variant="outline" size="sm" className="gap-2 rounded-lg h-9 border-border bg-card/50">
                            <Save className="w-4 h-4" />
                            Save
                        </Button>
                        <Button size="sm" className="gap-2 rounded-lg h-9 shadow-lg shadow-primary/20" onClick={runQuery} disabled={isRunning}>
                            {isRunning ? (
                                <RefreshCw className="w-4 h-4 animate-spin" />
                            ) : (
                                <Play className="w-4 h-4 fill-current" />
                            )}
                            {isRunning ? "Running..." : "Run Pipeline"}
                        </Button>
                    </div>
                </div>

                {/* Editor Area */}
                <div className="flex-1 flex flex-col overflow-hidden">
                    {/* Code Editor */}
                    <div className="flex-1 overflow-auto bg-card/5 p-8 scrollbar-thin">
                        <pre className="font-mono text-xs leading-relaxed">
                            {sql.split("\n").map((line, i) => {
                                const isComment = line.trim().startsWith("--");
                                const isKeyword = /^(SELECT|FROM|WHERE|JOIN|LEFT|RIGHT|INNER|OUTER|GROUP BY|ORDER BY|WITH|AS|CASE|WHEN|THEN|ELSE|END|AND|OR|ON|USING|COALESCE|COUNT|SUM|AVG|MAX|MIN|DATEDIFF|DATEADD)\b/i.test(line.trim());

                                return (
                                    <div key={i} className="flex group">
                                        <span className="w-12 text-right pr-6 text-muted-foreground/30 select-none font-mono">
                                            {i + 1}
                                        </span>
                                        <span
                                            className={cn(
                                                "transition-colors",
                                                isComment
                                                    ? "text-muted-foreground/60 italic"
                                                    : isKeyword
                                                        ? "text-primary font-bold"
                                                        : "text-foreground"
                                            )}
                                        >
                                            {line || " "}
                                        </span>
                                    </div>
                                );
                            })}
                        </pre>
                    </div>

                    {/* Results Panel */}
                    {showResults && (
                        <div className="h-80 border-t border-border flex flex-col bg-card/20 backdrop-blur-md">
                            <div className="h-12 border-b border-border px-6 flex items-center justify-between bg-card/40">
                                <div className="flex items-center gap-6">
                                    <div className="flex items-center gap-2">
                                        <Table className="w-4 h-4 text-muted-foreground" />
                                        <span className="text-xs font-bold uppercase tracking-widest text-foreground">Query Results</span>
                                    </div>
                                    <div className="h-4 w-px bg-border" />
                                    <span className="text-[10px] font-bold text-muted-foreground uppercase tracking-wider">
                                        124,521 rows scanned • 428ms execution
                                    </span>
                                </div>
                                <div className="flex items-center gap-2">
                                    <Button variant="ghost" size="sm" className="gap-2 h-8 text-[10px] font-bold uppercase tracking-wider hover:bg-secondary/50">
                                        <Download className="w-3.5 h-3.5" />
                                        Download CSV
                                    </Button>
                                    <Button variant="ghost" size="sm" className="w-8 h-8 p-0">
                                        <Maximize2 className="w-3.5 h-3.5 text-muted-foreground" />
                                    </Button>
                                </div>
                            </div>
                            <div className="flex-1 overflow-auto scrollbar-thin">
                                <table className="w-full text-left">
                                    <thead className="sticky top-0 bg-secondary/80 backdrop-blur-sm z-10">
                                        <tr className="border-b border-border">
                                            {Object.keys(dataPreview[0]).map((col) => (
                                                <th
                                                    key={col}
                                                    className="px-6 py-3 text-[10px] font-bold uppercase tracking-widest text-muted-foreground"
                                                >
                                                    {col}
                                                </th>
                                            ))}
                                        </tr>
                                    </thead>
                                    <tbody className="font-mono text-[11px] divide-y divide-border/30">
                                        {dataPreview.map((row, i) => (
                                            <tr key={i} className="hover:bg-primary/5 transition-colors">
                                                {Object.values(row).map((val, j) => (
                                                    <td key={j} className="px-6 py-3 text-foreground/80 font-medium">
                                                        {typeof val === "number" && val > 1000
                                                            ? val.toLocaleString()
                                                            : String(val)}
                                                    </td>
                                                ))}
                                            </tr>
                                        ))}
                                    </tbody>
                                </table>
                            </div>
                        </div>
                    )}
                </div>
            </div>

            {/* Right Panel - Co-Pilot & Profiling */}
            <div className="w-80 border-l border-border bg-card/40 backdrop-blur-xl flex flex-col">
                <div className="p-6 border-b border-border bg-card/60">
                    <h2 className="text-xs font-bold uppercase tracking-[0.2em] text-foreground flex items-center gap-3">
                        <Sparkles className="w-4 h-4 text-primary animate-pulse" />
                        AI Co-Pilot
                    </h2>
                </div>

                <div className="flex-1 overflow-y-auto p-6 space-y-6 scrollbar-thin">
                    <div className="space-y-3">
                        {copilotHints.map((hint, index) => (
                            <div
                                key={index}
                                className={cn(
                                    "p-4 rounded-2xl border transition-all hover:scale-[1.02] duration-200",
                                    hint.type === "warning"
                                        ? "bg-red-400/5 border-red-400/20"
                                        : hint.type === "suggestion"
                                            ? "bg-primary/5 border-primary/20"
                                            : "bg-secondary/30 border-border/50"
                                )}
                            >
                                <div className="flex items-start gap-3">
                                    {hint.type === "warning" ? (
                                        <AlertTriangle className="w-4 h-4 text-red-400 shrink-0 mt-0.5" />
                                    ) : hint.type === "suggestion" ? (
                                        <Lightbulb className="w-4 h-4 text-primary shrink-0 mt-0.5" />
                                    ) : (
                                        <CheckCircle className="w-4 h-4 text-emerald-400 shrink-0 mt-0.5" />
                                    )}
                                    <p className="text-[12px] leading-relaxed text-foreground font-medium">{hint.message}</p>
                                </div>
                            </div>
                        ))}
                    </div>

                    <div className="pt-2">
                        <h3 className="text-[10px] font-bold uppercase tracking-[0.2em] text-muted-foreground mb-4 flex items-center gap-2 px-1">
                            <Database className="w-3.5 h-3.5" />
                            Active Schema
                        </h3>
                        <div className="space-y-2">
                            {profilingStats.map((stat) => (
                                <div
                                    key={stat.column}
                                    className="p-3 rounded-xl bg-secondary/20 border border-border/50 group hover:border-primary/20 transition-all"
                                >
                                    <div className="flex items-center justify-between mb-1.5">
                                        <code className="text-xs font-mono font-bold text-primary group-hover:text-primary transition-colors">{stat.column}</code>
                                        <span className="text-[9px] font-bold uppercase tracking-tighter px-1.5 py-0.5 rounded bg-muted/50 text-muted-foreground">{stat.type}</span>
                                    </div>
                                    <div className="flex items-center gap-4 text-[10px] text-muted-foreground font-medium">
                                        <span className="flex items-center gap-1"><span className="w-1 h-1 rounded-full bg-red-400/30" />{stat.nullPct}% Null</span>
                                        <span className="flex items-center gap-1"><span className="w-1 h-1 rounded-full bg-primary/30" />{stat.distinct.toLocaleString()} Unique</span>
                                    </div>
                                </div>
                            ))}
                        </div>
                    </div>
                </div>

                <div className="p-6 border-t border-border bg-card/50 space-y-3">
                    <Button variant="outline" className="w-full gap-2 rounded-xl h-11 border-border font-bold text-xs uppercase tracking-wider">
                        <RefreshCw className="w-4 h-4" />
                        Refresh Schema
                    </Button>
                    <Button className="w-full gap-2 rounded-xl h-11 font-bold text-xs uppercase tracking-wider shadow-lg shadow-primary/10">
                        <FileCode className="w-4 h-4" />
                        Export Notebook
                    </Button>
                </div>
            </div>
        </div>
    );
}
